### ISSUE TITLE
Add unstructured metadata property to all models

### ISSUE THREAD

**Issue by jde** [coralproject/pillar#10]
__Challenge__: We need to account for metadata for all of our entities that varies from client to client.

__Solution__: Add a metadata property to every struct along with the endpoint code to capture it.

```
metadata map[interface{}]interface{}
```

This should allow us to capture any kind of data sent to pillar under the metadata attribute.

**Comment by ardan-bkennedy** [comment]
I suggest using a map[string]interface{} since this is a JSON document in Go.

May in code you want to use
map[string]map[string]interface{}

Map of field names and the corresponding sub-document.
