### ISSUE TITLE
Create endpoint to add indexes to mongo

### ISSUE THREAD

**Issue by jde** [coralproject/pillar#11]
__Challenge__: With variations in metadata, we cannot predict at the api level which fields will need to be queried.

__Solution__: Publish an endpoint with Pillar that creates an index on one or more fields.  The endpoint should accept 3 params:

```
collection: required, string, the name of the collection to index
keys: required, object, a json object to be dropped in the first argument of createIndex()*
options: optional, object, a json object to be dropped in the second argument of createIndex()*
```

__Note__: passing keys and options directly into the function call will allow us to take advantage of all of mongodb's indexing features, which are substantial: https://docs.mongodb.org/manual/reference/method/db.collection.createIndex/#db.collection.createIndex

Consumer: https://github.com/coralproject/sponge/issues/21

**Comment by samshub** [comment]
Agreed, we need to have an endpoint that allows us to create index on the fly.

**Comment by gabelula** [comment]
I'm assuming that we are calling this endpoint each time we are going importing the collection for the first time. Right? This is not something that is going to be updated regularly..

**Comment by samshub** [comment]
We can leverage the Index (https://godoc.org/labix.org/v2/mgo#Index) structure from mgo and simplify our use-case.

~~~
// Index denotes a request to add Index to various entities.
type Index struct {
	Target   string           `json:"target" bson:"target" validate:"required"`
 	Index    mgo.Index   `json:"index" bson:"index" validate:"required"`
}
~~~
