### ISSUE TITLE
Implement more form gallery functionality

### ISSUE THREAD

**Issue by jde** [coralproject/pillar#119]
Gallery
- [x] return identity info for each gallery answer delivered
- [ ] Make Gallery submissions historical
- [ ] Add field to store "Identity Fields to Show"
- [ ] Expose Publish Gallery endpoint (simply store snapshot of gallery for posterity)

**Comment by jde** [comment]
This ticket is on hold pending final ux/design gallery decision.

**Comment by kgardnr** [comment]
UX needed: https://trello.com/c/QkGEgPV1/26-gallery-ux-https-github-com-coralproject-pillar-issues-119

**Comment by kgardnr** [comment]
I'm going to close this as I think we have it covered in other tickets
