### ISSUE TITLE
Add env.list file for Pillar Docker startup

### ISSUE THREAD

**Issue by aiboyles** [coralproject/pillar#129]
In order to spin up a Docker container for Pillar, we use the command:
```
docker run --env-file ./env.list --publish 8080:8080 7b59c4c5efde
```

However, there is no existing env.list file that the user can edit--the user must create it from scratch. Other apps like Sponge have an existing env.list file in the main directory.

Having an existing env.list file in the main directory that the user can edit and then use would be very helpful and expedite the Docker installation process.

**Comment by alexbyrnes** [comment]
Should be fixed by #167
