### ISSUE TITLE
Leave search events should fire when a search is deleted

### ISSUE THREAD

**Issue by jde** [coralproject/pillar#139]
### Expected behavior

When a search is deleted, a leave search event should be fired for each user that was in that search.

### Actual behavior

The search is simply deleted without events for the users inside, effectively leaving them in a no longer existing search.

### Steps to reproduce behavior

- Create a search with users.
- Watch the enter search events.
- Delete the search.
- Note no leave search events.

**Comment by kgardnr** [comment]
Closing as we are not actively developing on Trust at this time.
