### ISSUE TITLE
Fix rabbitmq memory leak

### ISSUE THREAD

**Issue by jde** [coralproject/pillar#143]
We are seeing an ever increasing usage of memory coming from rabbitmq leading to server crashes.

**Comment by alexbyrnes** [comment]
premature close on this. Memory issue persisted over the weekend.  I'm having very good luck clearing the management console memory:

```shell 
rabbitmqctl eval 'supervisor2:terminate_child(rabbit_mgmt_sup_sup, rabbit_mgmt_sup), rabbit_mgmt_sup_sup:start_child().'
```

Most if not all of the memory appears to be devoted to stats collection in rmq.  Will wait a few days to confirm.

**Comment by jde** [comment]
The ``terminate_child(...)`` approach above resolved the issue.  No need to update Go.
