### ISSUE TITLE
API support for sorting/filtering/searching submissions

### ISSUE THREAD

**Issue by kgardnr** [coralproject/pillar#155]
Form Submissions

- [x] Search by term
- [ ] Order by date (asc, desc)
- [ ] Filter by (all, unflagged (default), flagged, bookmarked)
- [x] Page (skip, limit)

and the response having

Submission counts: 
- [ ] total (all responses)
- [ ] total (filtered)
- [ ] flagged
- [ ] bookmarked

This completes: https://github.com/coralproject/cay/issues/435

**Comment by gabelula** [comment]
We are going to return the total count of submissions for all the flags. plus the total of submissions in the system plus the count for the specific search. //cc @impronunciable @jde 
```
{
   submissions: [ formSubmissions ],
  count: {
    total_search : X
    total_submissions: X
    total_per_flag: {
       "flag": X
       ....
     }
  }
}
```

**Comment by gabelula** [comment]
"counts" instead of "count"

the total_per_flag is for the search so we are changing it to "search_by_flag"
