### ISSUE TITLE
Admin should see number of submissions per specific filter/sort/search

### ISSUE THREAD

**Issue by kgardnr** [coralproject/pillar#156]
Designs attached
![screenshot_2016-07-13_14 35 46](https://cloud.githubusercontent.com/assets/1077300/16864301/0fce579a-4a21-11e6-97ab-90a494954140.png)
![screenshot_2016-07-13_14 34 27](https://cloud.githubusercontent.com/assets/1077300/16864302/10dc4ff2-4a21-11e6-9ee2-2d6e9596eb8c.png)
![screenshot_2016-07-13_14 34 35](https://cloud.githubusercontent.com/assets/1077300/16864303/11d77bd4-4a21-11e6-9398-4e55ba312f95.png)
![screenshot_2016-07-13_14 34 45](https://cloud.githubusercontent.com/assets/1077300/16864304/12e0083e-4a21-11e6-8803-8ef0d2912bbf.png)

**Comment by impronunciable** [comment]
@kgardnr Is this for pillar? Aren't we already doing this?

**Comment by kgardnr** [comment]
@impronunciable yeah, I think this is a dupe but we said yesterday we would keep it and close it when we were sure it matched the designs. Is this basically the frontend for https://github.com/coralproject/pillar/issues/163?

**Comment by impronunciable** [comment]
oh I see, thanks!
