### ISSUE TITLE
Fix memory leak issue in deploy process

### ISSUE THREAD

**Issue by jde** [coralproject/pillar#159]
A memory leak issue as discovered in our docker compose install model and solved in #143.  Integrate this fix into our deployment files so that it doesn't happen for future clients.

**Comment by alexbyrnes** [comment]
This is in https://github.com/coralproject/trust/pull/1 as a cron job which is how I implemented it internally. Do you have a different destination in mind other than /trust?

**Comment by jde** [comment]
If there is code that we know should be run when the app is spun up, let's add it to the deployment flow. 

Also, let's add this note to the documentation under Trust install.  @aiboyles can assist.

**Comment by alexbyrnes** [comment]
@jde where is the deployment flow? Please let me know where I can commit the change to close this.

**Comment by jde** [comment]
The Trust install is here: https://github.com/coralproject/Proxy

**Comment by alexbyrnes** [comment]
Permission to coralproject/Proxy.git denied to alexbyrnes

**Comment by alexbyrnes** [comment]
Thanks @kgardnr 

[coralproject/proxy pull 13](https://github.com/coralproject/Proxy/pull/13)

**Comment by alexbyrnes** [comment]
@edefikh please accept or reject if you think the switch from rabbitmq is going to be too soon.

**Comment by alexbyrnes** [comment]
merge accepted, closing
