### ISSUE TITLE
Associate auto-incrementing id with form submissions

### ISSUE THREAD

**Issue by jde** [coralproject/pillar#163]
We would like to have an id for each form submission that starts at 1 and increments. This will allow users to remember submissions by number and to easily get a sense of the sequence of the submissions.

Solution:
Create a new field on form_submissions ``number int``.  The first submission should be 1, each subsequent submission should increment that number by 1.

**Comment by gabelula** [comment]
I do not understand specifically which would be the user case for this issue. I started adding a number field to the submissions but when I went into changing the endpoints I have the doubt on how we are going to use this in the front end.

**Comment by losowsky** [comment]
@gabelula Here's some user cases: 

1. Sharing the submissions link with someone else in the newsroom. "Take a look at entry 15". If there is no stable ID visible then there is no easy way of sharing information.

2. If the ID number changes every filter, it is confusing for the journalist to know what has happened - something that was number 2 on one list is number 4 on another

Any confusion about the numbering should be removed by the display of "4 of 11 submissions" written at the top of the column.

**Comment by jde** [comment]
Fixed and merged
