### ISSUE TITLE
Add search parameter on submission list endpoint

### ISSUE THREAD

**Issue by impronunciable** [coralproject/pillar#164]
### Expected behavior

`https://pillar_stg.coralproject.net/api/form_submissions/575eee0c3bc37e0005545613?skip=0&limit=10&search=Hi!` should return submissions matching the search parameter

### Actual behavior

Not implemented

### Steps to reproduce behavior

Paste the url in your browser

**Comment by gabelula** [comment]
The counts are without filtering . In this case we are going to do 2 queries for the same endpoint, one to get all the counts for the search for the form id and then next one to get all the values filtering by tags. //cc @jde
