### ISSUE TITLE
Code reorg (cleanup) and few model changes

### ISSUE THREAD

**Issue by samshub** [coralproject/pillar#21]
* The handler methods can all be consolidated into a single go file
* Few duplicates code in service and model can be consolidated into model for reuse
* Few model changes to make it simpler
  * user.user_name should be user.name
  * note.target_type should be note.target
  * action.target_type should be action.target

**Comment by jde** [comment]
This is a good opportunity to start using a web package to handle http requests. Wrapping each of our http handlers in importer.go will allow us to:

* centralize headers
* apply middleware (such as auth)
* CORS support (required for the fe to be able to access)
* cut down on repetitive code

Using https://github.com/ardanlabs/kit/tree/master/web will allow us to standardize auth, config and logging with Xenia, which will be essential for consistency across the project.

**Comment by ardan-bkennedy** [comment]
I also suggest reworking the source tree of the three Go projects to be the same as well.

app
cmd
pkg
vendor
config
tstdata

A repo is a project and a project has a single vendor folder.

**Comment by jde** [comment]
Moving my comment to https://github.com/coralproject/pillar/issues/23  Moving @ardan-bkennedy 's comment to https://github.com/coralproject/pillar/issues/24
