### ISSUE TITLE
Adopt web package

### ISSUE THREAD

**Issue by jde** [coralproject/pillar#23]
Let's start using a web package to handle http requests. Wrapping each of our http handlers in importer.go will allow us to:

Requirements:
* standardize behavior between all Coral services (features, config, etc.. need to be identical)
* centralize headers
* apply middleware (such as auth)
* cut down on repetitive code
* CORS support 
* JSONP support

Using https://github.com/ardanlabs/kit/tree/master/web will allow us to standardize auth, config and logging with Xenia, which will be essential for consistency across the project.

**Comment by samshub** [comment]
Pillar has been standardized with http://www.gorillatoolkit.org/ and https://github.com/codegangsta/negroni.
