### ISSUE TITLE
Docker build should use vendored code

### ISSUE THREAD

**Issue by buth** [coralproject/pillar#36]
The `go get` commands here are non-deterministic.

https://github.com/coralproject/pillar/blob/master/app/pillar/Dockerfile#L9-L12

The `GO15VENDOREXPERIMENT` would be useful here, but the structure of the repository does not lend itself to using it.

**Comment by samshub** [comment]
@buth What is your proposal on the structure of this project?

**Comment by buth** [comment]
I don't have a specific one, but including the Dockerfile at this subdirectory prevents the vendored packages from being present in the context sent to Docker during the build.

**Comment by samshub** [comment]
Dockerfile has been moved up.
