### ISSUE TITLE
Support CORS pre-flight requests

### ISSUE THREAD

**Issue by pablocubico** [coralproject/pillar#39]
We are using fetch() on the front-end, which uses a "cors" mode and sends a pre-flight OPTIONS request to ask for available methods on the API side. 

Using fetch's "no-cors" mode allows for some POST requests, but when using "no-cors" you can't consume the response body, which is quite crucial. So CORS it is.

I think the gorilla handlers do have support for OPTIONS requests, the docs aren't very clear on how to set it up, but you can see some of the options on the code.

See related PR: #38

**Comment by samshub** [comment]
@pablocubico Please go ahead and make the changes with these recommendations:

> routes.go
~~~
	//Options
	Route{"OPTIONS", "/*", handler.Options},
~~~

> handler.go
~~~
func Options(w http.ResponseWriter, r *http.Request, p map[string]string) {
	w.Header().Set("Access-Control-Allow-Origin", "*")
	w.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, PATCH, DELETE, OPTIONS")
	w.Header().Set("Access-Control-Allow-Headers", "Content-Type, Authorization")
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
}
~~~

**Comment by pablocubico** [comment]
Hey Sam! Somehow this didn't work for me, I couldn't even hit the endpoints using cURL. I'm not a Go expert, anyway...

**Comment by samshub** [comment]
Verified with @pablocubico.
