### ISSUE TITLE
Code instead of error when it is a duplicated row

### ISSUE THREAD

**Issue by gabelula** [coralproject/pillar#40]
Right now each time sponge send a row that is already in the coral system, we get an error. Before #29 is implemented it would be great to get a code when duplicated row instead of an error.

**Comment by jde** [comment]
There is strong consensus on [this stackoverflow question](http://stackoverflow.com/questions/3825990/http-response-code-for-post-when-resource-already-exists) to respond with a 409 Conflict status code.  The body should also return a human readable description of what the conflict is IMHO.

**Comment by samshub** [comment]
Although I made a fix for this in branch #41 upsert (issue #29) was more appropriate. So we'll go ahead and close this issue.
