### ISSUE TITLE
Create indexes on mongo collections

### ISSUE THREAD

**Issue by jde** [coralproject/pillar#5]
Pillar needs to create indexes that prevent table scans for all operations it handles.

db.collection.createindex() will not override existing indexes, so we can call createindex each time the server starts without incurring cost:

https://docs.mongodb.org/v3.0/reference/method/db.collection.createIndex/#db.collection.createIndex

Note, indexes should not be created in the background, as we want to ensure that they are in place before the server starts accepting requests.

**Comment by samshub** [comment]
Reviewed code and added indexes if it was missing:
https://github.com/coralproject/pillar/commit/c9825a01c5ee203af26e13c4e54ae9063056827a
https://github.com/coralproject/pillar/commit/f376373405ddc4fb801384a2b2cbd052f180f357

**Comment by samshub** [comment]
Closing this issue since a more generic approach to creating index will be available through Issue#11
