### ISSUE TITLE
New endpoint needed to update tags in Asset/User/Comment

### ISSUE THREAD

**Issue by samshub** [coralproject/pillar#56]
Front-end needs apis to update asset, user and comment with tags. At this time, the update will be limited to tags only, possibly needs expansion later in future.

**Comment by jde** [comment]
Here's the pattern I recommend for the tagging api:

```
api/tag/[user|comment|asset|...]/_id/[add|remove]/tagname
```
In this paradigm, single tags are added and removed to/from and entity.  This makes it so that the thing doing the request doesn't have to care about what other tags the entity may or may not have.

**Comment by pablocubico** [comment]
Looks good to me to minify the requests, right now we are sending a `User` document with the tags inside each time you add/remove a tag. This plays well with the way tags are added on the UI: one at a time.

Bear in mind that we also need a way to apply a tag to a list of users (i.e. bulk actions), which should be a very common case. 

To cover a user story such as: **[ Bob wants to apply the "senior" tag to all users created before 2010 ]**.

For such cases, maybe we can pluralize the third argument (`user|comment|asset` for `users|comments|assets`) and provide the IDs on the POST body, I wouldn't provide a list of IDs on the API call itself.

I'm thinking on other possible user stories that we may cover or not.

**Comment by jde** [comment]
The Update functionality is needed for the partner demo.  As it stands, when a user updates a tag, the only available endpoint is upsert:

https://github.com/coralproject/xenia/issues/113

But the id of a tag is the label of the tag, so instead up updating the tag another tag is entered in it's place.  Also, users will be expecting to be able to update a tag and have all instances of that tag across users change.

**Comment by samshub** [comment]
Since the name of the ```Tag``` is unique and serves as the ID field for Mongo, we have two choices (a) introduce ```ObjectId``` or (b) introduce a new field to keep the old name say ```old_name```.

The later approach has some advantages over the former. New field ```old_name``` will help take care of the use-case w/o rebuilding the data with ```ObjectId```. Also at any point, we’ll know what the last name was if the tag was ever renamed.

This change is minimal. For the use-case of rename, FE must pass the ```old_name``` while renaming.

**Comment by samshub** [comment]
Closed!
