### ISSUE TITLE
Data - Compute "meta stats subdocuments" 

### ISSUE THREAD

**Issue by jde** [coralproject/pillar#64]
__Challenge__: Provide a 'meta' level of stats on each stats packet calculated.

Each dimensional breakdown offers a consistent set of values.  In order to intelligently work with them (and build front ends to do so), we need to know information about what values we can expect, and how they are formed.  

Sample "meta stats" packet:
```
  min: // the minimum value in that dimension
  max: // the maximum
  mean: // the mean
  median:  // the median
  stdev: // the standard deviation value
  distribution: [ // a breakdown of the distribution of values in the range between man and max
    ##, // number of elements falling between 0% and 5% of range
    ##, // number of elements falling between 5% and 10% of range
    ...
    ## // number of elements falling between 95% and 100% of range
  ]
```

A meta stats packet must be provided _for each field in each dimensional breakdown_.  For example, we _might_ want to architect it this way:
```
  user_statistics.meta.comments.all.all.count: {
    // an entire meta stats packet for user_statistics.statistics.comments.all.all.count 
  }
```

This would allow a client who knows they want to work in a certain dimension to request a meta packet to render the interface for that dimension.

**Comment by jde** [comment]
Another option would be to break the meta stats out into another collection:

```
  user_statistics_meta.comments.all.all.count: {
    // an entire meta stats packet for user_statistics.statistics.comments.all.all.count 
  }
```
This may allow a user to more easily work with meta values alone across multiple dimension...  it also may not provide too much utility as this would _force_ two queries.

**Comment by impronunciable** [comment]
@losowsky This is blocking https://github.com/coralproject/cay/issues/145 on cay which is on To-Do. I think we need to either move this to To-Do or move the sparklines in cay to the backlog.

**Comment by losowsky** [comment]
@impronunciable Good spot. I'm going to move the Cay issue for now; if we can find the resources to solve this issue in this sprint, then we'll move both back. Thanks!
