### ISSUE TITLE
Update UserGroup model and endpoints to Search

### ISSUE THREAD

**Issue by samshub** [coralproject/pillar#76]
Define a new entity ```UserGroup``` and end-points for crud operations on it.

**Comment by jde** [comment]
Pillar should allow the front end to store UserGroup flexibly, only setting _id and date_created for inserts and date_updated for updates.

The full schema is expected to look like this, however may include extra fields.

```
_id
date_created time
date_updated time
name string
description string
created_by string
filters []filters
include_tags []tags
exclude_tags []tags
```

**Comment by samshub** [comment]
Here is how the model looks https://github.com/coralproject/pillar/blob/Issue%2376/pkg/model/user_group.go.

Please note a slight change in the naming of various fields to be consistent with other fields:
~~~
	date_created time
	date_updated time
	user_created string
	user_updated string
~~~

**Comment by jde** [comment]
We are ditching the concept of UserGroup for the simpler concept of search.  Searches have the following form:

```
_id

name string 
description string

query_set string // the name of the xenia query set for this search

live_tag string // the name of the live tag to be added to users meeting this search

filters []interface{} // the filter definition will be owned by the front end

results []interface{} // an array of documents returned from xenia (to be set by Live Tagging Process)

created_by string
date_created time
date_updated time
```

**Comment by samshub** [comment]
Here are the end-points for Search
~~~
GET api/searches
POST api/search
DELETE api/search
~~~

**Comment by jde** [comment]
I added PUT to support front end semantics.

```
GET api/searches
PUT api/search
POST api/search
DELETE api/search
```

PR merged.

**Comment by samshub** [comment]
Also here is an example snippet of Search json

~~~
{
        "name": "name-of-search",
        "description": "description-of-search",
        "query" : "actual-query-string",
        "tag" : "name-of-tag",
        "filters" : "can-be-a-json",
        "results" : "can-be-a-json"
}
~~~
