### ISSUE TITLE
Create search_history collection

### ISSUE THREAD

**Issue by jde** [coralproject/pillar#77]
__Challenge__: As searches change over time, people will want to be able to see what the effects of those changes are.  In anticipation of this, we need to create a history of creates and updates that store each search state along the way.  

__Solution__: Create a search_history collection and update it whenever a search is created or updated.  Documents should look like this:

```
{
  action: "[create|update]",
  when: date,
  search: { full user group record }
}
```

**Comment by samshub** [comment]
Closed!
