### ISSUE TITLE
Create Live Tagging Functionality

### ISSUE THREAD

**Issue by jde** [coralproject/pillar#79]
This process' job is to keep the tags on a user in sync with the Searches that that user falls under.  

The goals of this process are: 

* to add a live tag to users that are returned by a search now, but weren't the last time this job was run. 
* to remove the live tag from users who were in this search, but aren't anymore
* to trigger an event when a tag is added or removed
* to set the search.results field to the current users returned by the search 
* to store a snapshot of the current search for historical purposes in a search_history collection

Some pseudocode
```
Query the collection searches
For each search

  Find the users who were in the search last time we ran it (they will have the tag)
  Find users who already have search.live_tag: previous_users_in_search

  Run the search by hitting xenia with the query_set name
  receive a list: current_users_in_search

  For each user that enters the search (not in previous_users && in current_users)
    Add search.live_tag to that user
    trigger an event that this user has entered the search
    
  For each user that is no longer in the search (not in current_users && in previous_users)
    Remove search.live_tag from that user
    trigger an event that this user has left the search
    
  Save the current_users_in_search into search.results

  Save the current_users_in_search into the search_results_history collection with timestamp
    
/end for each search
```

**Comment by jde** [comment]
We need to limit the maximum number of users who can be live tagged by a single search.  

Create a config field and disable live tagging if the results of a search are greater than that number.

**Comment by samshub** [comment]
Part 1 - Added a cron job that runs every few intervals and runs the algorithm. So far it adds/removed tags.

**Comment by samshub** [comment]
Part 2 : Control cron and the job from env. More coming....

Part 3 : Added new vendors github.com/robfig/cron and github.com/stretchr/stew/objects.

Part 4 : Events are being fired and search result is saved in search.result.

**Comment by samshub** [comment]
Completed.
