### ISSUE TITLE
Allow notes on Comments and Users

### ISSUE THREAD

**Issue by jde** [coralproject/pillar#8]
__Challenge__: The Trust product will allow users to leave notes on comments or users.  Most of our source data structures only allow comments on notes.  Our schema will need to allow notes to be placed on documents in any collection.

__Concept__: Notable (aka, "Comments and Users are Notable")

__Spec__
* Build CRUD apis for notes
  * [POST, GET, PUT && Delete] /notes/ 
* Implement note counts on comments/users
* Implement strategy to return notes along with comments/users

__3 possible solutions__ depending on how we end up dealing with relations in mongo:
* Append notes to a subdocument on the document, 
* Create a separate notes collection.  Each document has a field indicating which document the note is on, or
* Create separate noes collections for notes on each document type.  aka, make user_notes and comment_notes collections for notes on users and comments respectively.

**Comment by samshub** [comment]
Added a new endpoint to append notes to Comment and User. At this time, I've not made Note as a separate collection. This is something we should discuss and finalize.
