### ISSUE TITLE
Stats: Write directly to user collection

### ISSUE THREAD

**Issue by jde** [coralproject/pillar#80]
__Situation__: in the past we have been writing stats to a user_statistics collection in order to keep the user collection concise.  We are now rigorously using the $project operator when querying from the front end allowing us to specifically choose exactly which fields we want, so this is no longer an issue.

__Solution__: Update stats code so that it writes to users.statistics.  Leave the user_references functionality as is.  We have no more use for the user_statistics collection.

**Comment by kgardnr** [comment]
Won't fix
