### ISSUE TITLE
Stats: Create configurable formulas to describe user archetypes

### ISSUE THREAD

**Issue by jde** [coralproject/pillar#81]
__Situation__: We currently have basic count, average and date capabilities hard coded into our aggregations.  

Our clients would like to be able to use these values in basic mathematical formulas to produce values.

The formulas will be a bridge between flat statistical numbers and product focused user archetypes.  We will be able to _describe_ behavior that points to different user characteristics and characterize them appropriately.

Examples to follow in comments

**Comment by losowsky** [comment]
It's an interesting idea – I think it's a 2017 question.
