### ISSUE TITLE
Populate Search.Responses each time a query is run.

### ISSUE THREAD

**Issue by jde** [coralproject/pillar#84]
Each time a query is run by the auto tagger, we should cache the Response field of the search.  This will allow the front end to render counts and initial user lists without needing to execute the queries.

The following two fields should be returned:

Search.Response.Content - the top 30 users sorted by comments descending* 
Search.Response.Count - the number of users returned in the search

(* - in the future we may want to make this more flexible to return different sorts / more users, but for this iteration the top 30 will do.)

**Comment by losowsky** [comment]
Me with @riley
