### ISSUE TITLE
Create Event based api push mechanism

### ISSUE THREAD

**Issue by jde** [coralproject/pillar#89]
We need a generic mechanism that:

1) when an event is triggered (or, we call a function)
2) we hit an api endpoint 
3) with data

The first usage will be to hit WaPo's add/remove tag api when users are give live tags.

**Comment by samshub** [comment]
This is completed. As part of integration, I've now code for WaPo named `wake`. This code is designed to listen to `PIllar` events and react to them. So far, it reacts to two events:
> On `Asset` imported/created/updated => goes out and fetches the details for an `Asset`, updates it through `Pillar` again.
> On `Tag` added/removed to `User` => Talks to reverb and update the user's markers there.

This code is internal to WaPo.
