### ISSUE TITLE
Build Tag APIs

### ISSUE THREAD

**Issue by jde** [coralproject/pillar#9]
__Challenge__: The Trust product requires the ability to apply tags to users.

__Concept__: Taggable ("Users are Taggable")

__Spec__
* Create tags collection to hold all possible tags:
``` 
{
  _id: type ObjectId()
  name: type string, // required, not empty, unique
  group: type string // default 'users'
}
```
* Expose CRUD endpoints for Tags
  * [POST, PUT, GET, DELETE] /tags/
* Design reference scheme (similar to Issue #8) to associate tags with users
  * We should have the ability to assign tags to any document in any collection

**Comment by samshub** [comment]
Defining two collections to hold this data:

~~~
// Tag denotes a unique tag in the system
type Tag struct {
	Name        string    `json:"name" bson:"_id" validate:"required"`
	Description string    `json:"description" bson:"description" validate:"required"`
	DateCreated time.Time `json:"date_created" bson:"date_created"`
	DateUpdated time.Time `json:"date_updated" bson:"date_updated"`
}

// TagStat denotes relationship between an entity and tags
type TagStat struct {
	ID          bson.ObjectId `json:"id" bson:"_id"`
	Target      string        `json:"target" bson:"target" validate:"required"`
	TargetID    bson.ObjectId `json:"target_id" bson:"target_id" validate:"required"`
	Tag         string        `json:"tag" bson:"tag" validate:"required"`
	DateCreated time.Time     `json:"date_created" bson:"date_created"`
}
~~~

**Comment by samshub** [comment]
In addition, there will be ```Tags``` array in ```User```, ```Asset``` and ```Comment```

~~~
	Tags         []string        `json:"tags,omitempty" bson:"tags,omitempty"`
~~~

**Comment by jde** [comment]
Looks good except two things:

1) Change TagStat to TagTarget (referring to the collection coral_tag_target).  The clearest standard I've seen for reference tables is to have the two entities that they are joining in the name in alphabetical order.  Also, we are using the term Stat to describe statistics objects.

2) It is going to get confusing to remember that Tag.Name needs to be compared with TagStat.Tag in Go and tags._id refers to tag_stats.tag in mongo.

I propose this structure:

~~~
// Tag denotes a unique tag in the system
// collection: coral_tags
type Tag struct {
	Name        string    `json:"name" bson:"name" validate:"required"`
	Description string    `json:"description" bson:"description" validate:"required"`
	DateCreated time.Time `json:"date_created" bson:"date_created"`
	DateUpdated time.Time `json:"date_updated" bson:"date_updated"`
}

// TagRef denotes relationship between an entity and tags
// collection coral_tags_targets
type TagTarget struct {
	ID          bson.ObjectId `json:"id" bson:"_id"`
	Target      string        `json:"target" bson:"target" validate:"required"`
	TargetID    bson.ObjectId `json:"target_id" bson:"target_id" validate:"required"`
	Name         string        `json:"name" bson:"name" validate:"required"`
	DateCreated time.Time     `json:"date_created" bson:"date_created"`
}
~~~

Doing it this way makes "name" the canonical var for the name of the tag in Go and bson, in both manifestations.

**Comment by pablocubico** [comment]
Looks like only POST is being handled so far by routes.go (https://github.com/coralproject/pillar/blob/master/app/pillar/route/routes.go).

Should we reopen this to add GET, PUT and DELETE? Adding tags via POST works fine from the tag manager.

Waiting for directions on this.

**Comment by samshub** [comment]
Reopening this - didn't realize this was being used from the Front-End.

**Comment by pablocubico** [comment]
This is what it looks like so far!

- GET would happen when the UI is entered
- then PUT will be triggered if a Tag name is updated
- DELETE from the delete buttons
- POST from the top addition input (this one is already working perfectly)

![tag-manager-ui](https://cloud.githubusercontent.com/assets/340766/12757377/87a0294c-c9b6-11e5-9d6a-fa128c895513.JPG)

**Comment by samshub** [comment]
Here is a summary: 

~~~
GET    /api/tags - returns all tags
POST   /api/tag  - creates/updates (pass json body)
DELETE /api/tag  - deletes the tag (pass json body)
~~~

Here is an example of the json body

~~~
  {
    "name": "troll",
    "description": "An internet troll (https://en.wikipedia.org/wiki/Internet_troll)"
  }
~~~
