### ISSUE TITLE
Integrate Pillar with Atoll

### ISSUE THREAD

**Issue by impronunciable** [coralproject/pillar#91]
To provide meaningful NLP stats for our users.

**Comment by gabelula** [comment]
Yes. I think it makes sense to start integrating Atoll and do all the aggregation stuff that we are doing in Stats in Pillar with Atoll.

**Comment by alexbyrnes** [comment]
[This example](https://github.com/coralproject/atoll/blob/coral-stats-test/examples/coral/userWordCount.py) might be a good place to start.  Gets average word counts a la Pillar. 

Scaling this will depend on a variety of factors that I think we should sort out as soon as we can.  Really (very) roughly speaking if a site gets 10k comments a day I think this will be fine.

**Comment by alexbyrnes** [comment]
[42 aggregations](https://github.com/coralproject/atoll/commit/ca69367db967cfd3b00ea979167c9858ea6e34fc) that are currently in pillar.

**Comment by alexbyrnes** [comment]
These are in the coralproject/stats repo. Similar approach but keeping things that were meant to be done with the atoll library as a dependency out of atoll proper.  The first stat that depends on the body of the comment is there now too. Feel free to give feedback/pr.
